OOP School Library Milestone: Add basic UI
CarlosIgreda/OOP-school-library pull request #4
Opened 2023-07-08 09:13 UTC by CarlosIgreda

For this milestone I:

✅ Used GitFlow
✅ Built interactive console apps
✅ Ran a program using the command line

2023-07-08 09:36 UTC, Ismailco requested changes
### Hi @CarlosIgreda, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 09:36 UTC, Ismailco commented on main.rb
> +app.main
- [ ] The main method should be present in the main.rb file instead of app.rb, and invoked at the end of the file to serve as the entry point for the app

2023-07-08 09:36 UTC, Ismailco commented on app.rb
> +      '7' => method(:exit)
- [ ] [OPTIONAL] For some reason exiting the app using option 7 triggers an infinite loop, which crashes the app

2023-07-08 17:11 UTC, CarlosIgreda commented on main.rb
> +app.main
@Ismailco, thanks for your feedback.

2023-07-08 17:21 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![Ukhv](https://user-images.githubusercontent.com/93039359/247195854-e274f284-2e3a-423b-8939-7e4efb638ee0.gif)

## Hey @CarlosIgreda :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements
✔️ Great work on adding `main` and `menu` methods in main.rb file

Good job on implementing some of the requested changes, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 17:21 UTC, HAMMAS-SALEEM commented on main.rb
> +  end
- [ ] It's great that you have added the `menu` & `main` methods in the main.rb file 👍 but i guess you have added the App class into main.rb file which is against the project requirements 😊 Kindly put all the other functionality in the App class into the app.rb file and only `menu` & `main` methods should be in the main.rb 🤔

2023-07-08 17:21 UTC, HAMMAS-SALEEM commented on README.md
**[OPTIONAL REQUIREMENTS]**

- [ ] It would be nice if you make your own logo of your name and put that in the readme file at the top to present yourself as a brand in the job market or tech industry to catch the recruiters' eyes 👍

2023-07-08 17:55 UTC, CarlosIgreda commented on main.rb
> +  end
@HAMMAS-SALEEM, thank you for your feedback. The required changes are done.

2023-07-08 18:30 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @CarlosIgreda, 

To highlight 👍🏽 
✔️ `Main.rb` is the entry point
✔️ App matches wireframe

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 18:30 UTC, Ghiftee commented on app.rb
> +    exit
- [OPTIONAL] As the first reviewer mentioned, an infinite loop crashes your app when the menu option 7 is pressed to exit the app. The problem lies in the method name `exit`, which conflicts with the exit method provided by Ruby itself. This conflict prevents the application from exiting properly. To fix this, you can do the following:

In `app.rb` rename the `exit` function eg:

``` ruby 
def exit_application
    puts 'Thank you for using this app!'
    exit
  end
```
In `main.rb` update the exit_app function thus:

```ruby
def exit_app
  @app.exit_application
end

2023-07-08 18:39 UTC, merged

2023-07-08 18:44 UTC, CarlosIgreda commented on app.rb
> +    exit
@Ghiftee, thank you for this feedback! I really appreciate it, now it's working properly.

2023-07-08 18:50 UTC, CarlosIgreda commented
@Ghiftee, thank you so much for your feedback!

2023-07-10 09:08 UTC, Ghiftee commented on app.rb
> +    exit
@CarlosIgreda You're welcome!